language: go

go:
  - "1.11.4"

install: true
notifications:
  email: false

env:
  - GO111MODULE=on

jobs:
  include:
    - stage: Test
      script:
        - go get -v -d
        - go test -v -cover